---
group:
  fiddle_leaf_fig:
    name: Fiddle Leaf Fig
    entities:
      - sensor.fiddle_leaf_fig_moisture
      - sensor.fiddle_leaf_fig_temperature
      - sensor.fiddle_leaf_fig_fertility
      - sensor.fiddle_leaf_fig_brightness
  fiddle_leaf_fig_automations:
    name: Fiddle Fig
    entities:
      - input_boolean.fiddle_leaf_fig_automation_low_moisture

sensor:
  - platform: mqtt
    state_topic: "plantgateway/plants/fiddle_leaf_fig/"
    name: Fiddle Leaf Fig Battery
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery }}'
    device_class: battery
  - platform: mqtt
    state_topic: "plantgateway/plants/fiddle_leaf_fig/"
    name: Fiddle Leaf Fig Brightness
    unit_of_measurement: lx
    value_template: '{{ value_json.brightness }}'
    device_class: illuminance
  - platform: mqtt
    state_topic: "plantgateway/plants/fiddle_leaf_fig/"
    name: Fiddle Leaf Fig Fertility
    unit_of_measurement: "μs/cm"
    value_template: '{{ value_json.conductivity }}'
  - platform: mqtt
    state_topic: "plantgateway/plants/fiddle_leaf_fig/"
    name: Fiddle Leaf Fig Moisture
    unit_of_measurement: "%"
    value_template: '{{ value_json.moisture }}'
  - platform: mqtt
    state_topic: "plantgateway/plants/fiddle_leaf_fig/"
    name: Fiddle Leaf Fig Temperature
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature }}'
    device_class: temperature
