---
group:
  living_room_tv:
    name: TV
    control: hidden
    entities:
      - remote.samsung_tv
      - switch.media_center
      - switch.ps4
      - scene.watch_plex

media_player:
  - platform: roku
    host: roku.phil.lan

remote:
  - platform: harmony
    name: Samsung TV
    host: harmony-hub.phil.lan
    activity: 22580039

script:
  switch_roku_to_plex:
    sequence:
      - service: media_player.select_source
        data:
          entity_id: media_player.roku_yp005n794105
          source: Plex

scene:
  name: Watch Plex
  entities:
    switch.media_center:
      state: true
    remote.samsung_tv:
      state: true
    script.switch_roku_to_plex:
      state: true

sensor:
  - platform: template
    sensors:
      roku_source:
        friendly_name: Roku Source
        value_template: >
          {{ states.media_player.roku_yp005n794105.attributes.app_name }}
        icon_template: >
          {%
            set state =
              states.media_player.roku_yp005n794105.attributes.app_name
          %}
          {% if state == 'Netflix'%}
            mdi:netflix
          {% elif state == 'Hulu'%}
            mdi:hulu
          {% elif state == 'XFINITY Stream'%}
            mdi:television-classic
          {% elif state == 'YouTube'%}
            mdi:youtube-play
          {% elif state == 'Aquatic Life'%}
            mdi:fish
          {% elif state == 'Plex'%}
            mdi:plex
          {% else %}
            mdi:apps
          {% endif %}

shell_command:
  turn_off_media_center: 'ssh bachya@media-center.phil.lan sudo /sbin/poweroff'

switch:
  - platform: command_line
    switches:
      ps4:
        friendly_name: Playstation 4
        command_on: 'ps4-waker -c /config/.ps4-waker.json'
        command_off: 'ps4-waker -c /config/.ps4-waker.json standby'
        command_state: 'nc -z -w 5 ps4.phil.lan 9295'
  - platform: wake_on_lan
    mac_address: 4C:CC:6A:69:90:D4
    name: Media Center
    host: media-center.phil.lan
    turn_off:
      service: shell_command.turn_off_media_center
