---
group:
  wolfie:
    name: Wolfie
    control: hidden
    entities:
      - switch.wolfie_cycle
      - input_select.wolfie_bin_status
      - sensor.vacuum_status
      - sensor.vacuum_do_not_disturb
      - sensor.vacuum_battery
      - sensor.vacuum_fan_speed
      - sensor.vacuum_cleaning_time
      - sensor.vacuum_cleaned_area
      - input_boolean.vacuum_schedule_monday
      - input_boolean.vacuum_schedule_tuesday
      - input_boolean.vacuum_schedule_wednesday
      - input_boolean.vacuum_schedule_thursday
      - input_boolean.vacuum_schedule_friday
      - input_boolean.vacuum_schedule_saturday
      - input_boolean.vacuum_schedule_sunday
  wolfie_automations:
    name: Wolfie
    entities:
      - input_boolean.wolfie_automation_monitor_consumables
      - input_boolean.wolfie_automation_scheduled_cycle

input_boolean:
  vacuum_schedule_monday:
    name: 'Monday'
    icon: mdi:calendar
    initial: true
  vacuum_schedule_tuesday:
    name: 'Tuesday'
    icon: mdi:calendar
    initial: false
  vacuum_schedule_wednesday:
    name: 'Wednesday'
    icon: mdi:calendar
    initial: false
  vacuum_schedule_thursday:
    name: 'Thursday'
    icon: mdi:calendar
    initial: true
  vacuum_schedule_friday:
    name: 'Friday'
    icon: mdi:calendar
    initial: false
  vacuum_schedule_saturday:
    name: 'Saturday'
    icon: mdi:calendar
    initial: false
  vacuum_schedule_sunday:
    name: 'Sunday'
    icon: mdi:calendar
    initial: false

input_select:
  wolfie_bin_status:
    name: Bin Status
    options:
      - Empty
      - Full

sensor:
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: Status
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}
        icon_template: >
          {% set val = states.vacuum.xiaomi_vacuum_cleaner.attributes.status %}
          {% if val == 'Charging' %}
            mdi:battery-charging
          {% elif val == 'Cleaning' %}
            mdi:move-resize
          {% elif val == 'Returning home' %}
            mdi:keyboard-return
          {% elif val == 'Idle' %}
            mdi:dots-horizontal
          {% elif val == 'Paused' %}
            mdi:pause-circle
          {% else %}
            mdi:help-circle
          {% endif %}
      vacuum_fan_speed:
        friendly_name: Fan Speed
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.fan_speed }}
        icon_template: mdi:speedometer
      vacuum_battery:
        friendly_name: Vacuum Battery
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_level }}
        unit_of_measurement: "%"
        icon_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.battery_icon }}
      vacuum_cleaning_time:
        friendly_name: Time of Last Cycle
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}
        icon_template: mdi:timer
      vacuum_cleaned_area:
        friendly_name: Area of Last Cycle
        unit_of_measurement: m ²
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}
        icon_template: mdi:ruler
      vacuum_do_not_disturb:
        friendly_name: Do Not Disturb
        value_template: >
          {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb }}
        icon_template: >
          {%
            set val =
              states.vacuum.xiaomi_vacuum_cleaner.attributes.do_not_disturb
          %}
          {% if val == 'on' %}
            mdi:do-not-disturb
          {% else %}
            mdi:do-not-disturb-off
          {% endif %}

switch:
  - platform: template
    switches:
      wolfie_cycle:
        friendly_name: Activate
        value_template: "{{ is_state('sensor.vacuum_status', 'Cleaning') }}"
        icon_template: 'mdi:google-circles-group'
        turn_on:
          event: VACUUM_START
        turn_off:
          service: vacuum.turn_off
          data:
            entity_id: vacuum.xiaomi_vacuum_cleaner

vacuum:
  - platform: xiaomi_miio
    host: rockrobo.phil.lan
    token: !secret xiaomi_vacuum_token
