---
- platform: pushbullet
  name: amb_macbook
  api_key: !secret pushbullet_api_key
- platform: smtp
  name: omnifocus
  server: smtp.gmail.com
  port: 587
  timeout: 15
  username: !secret omnifocus_maildrop_username
  password: !secret omnifocus_maildrop_password
  sender: !secret omnifocus_maildrop_username
  sender_name: Home Assistant
  recipient: !secret omnifocus_maildrop_recipient
